# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use a Node.js image with the latest LTS version
FROM node:18-alpine AS builder

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json for installing dependencies
COPY package.json /app/
COPY tsconfig.json /app/

# Install dependencies
RUN npm install --ignore-scripts

# Copy the rest of the application files
COPY ./src /app/src

# Build the TypeScript project
RUN npm run build

# Use a smaller Node.js image for running the application
FROM node:18-alpine AS release

# Set the working directory
WORKDIR /app

# Copy the build from the builder
COPY --from=builder /app/build /app/build

# Copy package.json for production installation
COPY package.json /app/

# Set environment variables for production
ENV NODE_ENV=production
ENV NODE_OPTIONS=--max-old-space-size=256
ENV npm_config_cache_max=1024000000

# Install production dependencies
RUN npm ci --only=production

# Expose port if needed
# EXPOSE 3000

# Run the application
CMD ["node", "build/index.js"]